#!/usr/bin/env bash

. `dirname $0`/vars

docker run -p $LOCAL_PORT:2222 --rm \
  -e "SSH_USER=$SSH_USER" \
  -e "SSH_GROUP=$SSH_GROUP" \
  -e "AUTHORIZED_KEYS=$AUTHORIZED_KEYS" \
  -e "ALLOWED_IPS=$ALLOWED_IPS" \
  -it $CONTAINER_NAME