#!/usr/bin/env bash

. `dirname $0`/vars

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}") 

if [[ "$(docker images -q $CONTAINER_NAME 2> /dev/null)" == "" ]]; then
  docker -l "debug" build -t $CONTAINER_NAME ${SCRIPT_DIR}/../../config/
fi