#!/usr/bin/env bash

. `dirname $0`/vars

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}") 

chmod 600 ${SCRIPT_DIR}/../../config/id_ed25519

ssh -o StrictHostKeyChecking=no -o "UserKnownHostsFile=/dev/null" -o "LogLevel ERROR" --access-with ./config/id_ed25519 dotcontract@localhost -p $SSH_PORT -x $1