#!/usr/bin/env bash

. `dirname $0`/vars

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}") 

if [[ "$(docker images -q $IMAGE_NAME 2> /dev/null)" == "" ]]; then
  docker -l "debug" build -t $IMAGE_NAME ${SCRIPT_DIR}/../../config/
fi