[package]
name = "kripke-machine"
version = "0.1.0"
edition = "2021"
description = "evolving logic machine"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
